;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	beginning-of-visual-line
	dabbrev-expand
	end-of-visual-line
	kill-region
	kill-visual-line
	org-self-insert-command
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	autopair-newline
	autopair-skip-close-maybe
	beginning-of-buffer
	c-electric-slash
	electric-indent-just-newline
	isearch-repeat-forward
	mark-whole-buffer
	move-line-down
	move-line-up
	sgml-slash
	))
